name: Sync Issues to Project2

on:
  issues:
    types:
      - opened
      - labeled

jobs:
  add-to-project2:
    name: Add issue to Project2
    runs-on: ubuntu-latest
    if: github.event.issue.labels.*.name contains 'PMS' # PMSラベルが付いている場合のみ実行
    steps:
      - uses: actions/add-to-project@RELEASE_VERSION
        with:
          project-url: https://github.com/users/39TO/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: PMS
          label-operator: AND
